---
name: Carthage
schemes:
  PackageDescription4:
    build:
      targets:
        PackageDescription4: build
  clibc:
    build:
      targets:
        clibc: build
  SPMLibc:
    build:
      targets:
        SPMLibc: build
  Basic:
    build:
      targets:
        Basic: build
  SPMUtility:
    build:
      targets:
        SPMUtility: build
  SourceControl:
    build:
      targets:
        SourceControl: build
  SPMLLBuild:
    build:
      targets:
        SPMLLBuild: build
  PackageModel:
    build:
      targets:
        PackageModel: build
  PackageLoading:
    build:
      targets:
        PackageLoading: build
  PackageGraph:
    build:
      targets:
        PackageGraph: build
  Build:
    build:
      targets:
        Build: build
  Xcodeproj:
    build:
      targets:
        Xcodeproj: build
  Workspace:
    build:
      targets:
        Workspace: build
  Commands:
    build:
      targets:
        Commands: build
  swift-package:
    build:
      targets:
        swift-package: build
  swift-build:
    build:
      targets:
        swift-build: build
  swift-run:
    build:
      targets:
        swift-run: build
targets:
  PackageDescription4:
    dependencies: []
    type: framework
    platform: macOS
    sources: Sources/PackageDescription4
  clibc:
    dependencies: []
    type: framework
    platform: macOS
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      INFOPLIST_FILE: plist/Info.plist
      MODULEMAP_FILE:
        - $(SRCROOT)/Sources/clibc/include/module.modulemap
    sources: Sources/clibc
  SPMLibc:
    dependencies:
    - target: clibc
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      INFOPLIST_FILE: plist/Info.plist
    type: framework
    platform: macOS
    sources: Sources/SPMLibc
  Basic:
    dependencies:
    - target: SPMLibc
    type: framework
    platform: macOS
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      INFOPLIST_FILE: plist/Info.plist
      SWIFT_VERSION: 4.2
    sources: Sources/Basic
  SPMUtility:
    dependencies:
    - target: Basic
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      INFOPLIST_FILE: plist/Info.plist
    type: framework
    platform: macOS
    sources: Sources/SPMUtility
  SourceControl:
    dependencies:
    - target: Basic
    - target: SPMUtility
    type: framework
    platform: macOS
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      SWIFT_VERSION: 4.2
    sources: Sources/SourceControl
  SPMLLBuild:
    dependencies:
    - target: Basic
    - target: SPMUtility
    - carthage: llbuildSwift
    - carthage: libllbuild
    - carthage: llbuildBuildSystem
    - carthage: llbuildCore
    - carthage: llbuildBasic
    - carthage: llvmSupport
    - carthage: llvmDemangle
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      INFOPLIST_FILE: plist/Info.plist
    type: framework
    platform: macOS
    sources: Sources/SPMLLBuild
  PackageModel:
    dependencies:
    - target: Basic
    - target: SPMUtility
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    type: framework
    platform: macOS
    sources: Sources/PackageModel
  PackageLoading:
    dependencies:
    - target: Basic
    - target: PackageModel
    - target: SPMUtility
    - target: SPMLLBuild
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    type: framework
    platform: macOS
    sources: Sources/PackageLoading
  PackageGraph:
    dependencies:
    - target: Basic
    - target: PackageLoading
    - target: PackageModel
    - target: SourceControl
    - target: SPMUtility
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    type: framework
    platform: macOS
    sources: Sources/PackageGraph
  Build:
    dependencies:
    - target: Basic
    - target: PackageGraph
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    type: framework
    platform: macOS
    sources: Sources/Build
  Xcodeproj:
    dependencies:
    - target: Basic
    - target: PackageGraph
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    type: framework
    platform: macOS
    sources: Sources/Xcodeproj
  Workspace:
    dependencies:
    - target: Basic
    - target: Build
    - target: PackageGraph
    - target: PackageModel
    - target: SourceControl
    - target: Xcodeproj
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    type: framework
    platform: macOS
    sources: Sources/Workspace
  Commands:
    dependencies:
    - target: Basic
    - target: Build
    - target: PackageGraph
    - target: SourceControl
    - target: SPMUtility
    - target: Xcodeproj
    - target: Workspace
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      INFOPLIST_FILE: plist/Info.plist
    type: framework
    platform: macOS
    sources: Sources/Commands
  swift-package:
    dependencies:
    - target: Commands
    type: application
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    platform: macOS
    sources: Sources/swift-package
    scheme:
      gatherCoverageData: true
      commandLineArguments:
        "--help": false
        "generate-xcodeproj": true
        "--package-path=${PWD}/temp/spm": true
      environmentVariables:
        - variable: SWIFTPM_CUSTOM_BINDIR
          value: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
          isEnabled: true
  swift-build:
    dependencies:
    - target: Commands
    type: application
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    platform: macOS
    sources: Sources/swift-build
  swift-run:
    dependencies:
    - target: Commands
    type: application
    settings:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    platform: macOS
    sources: Sources/swift-run